#!/bin/bash
sudo apt-get update
sudo mkdir -m 0755 -p /etc/apt/keyrings

wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install \
    build-essential \
    autoconf \
    libffi-dev \
    libssl-dev \
    zlib1g-dev \
    liblzma-dev \
    vagrant \
    qemu-kvm \
    libvirt-daemon-system \
    libvirt-dev \
    --yes
sudo adduser root libvirt
sleep 5
/usr/bin/vagrant plugin install vagrant-libvirt
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin --yes
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
mv kubectl /usr/local/bin/
chmod +x /usr/local/bin/kubectl
ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
ssh-keyscan github.com >> ~/.ssh/known_hosts
QEMU_CONF="/etc/libvirt/qemu.conf"
set_security_driver_none() {
    if grep -q '^#security_driver = "selinux"' $QEMU_CONF; then
        sudo sed -i 's/#security_driver = "selinux"/security_driver = "none"/' $QEMU_CONF
    elif grep -q '^security_driver = "selinux"' $QEMU_CONF; then
        sudo sed -i 's/security_driver = "selinux"/security_driver = "none"/' $QEMU_CONF
    else
        echo 'security_driver = "none"' | sudo tee -a $QEMU_CONF
    fi
}
set_security_driver_none
sudo systemctl restart libvirtd

until systemctl is-active --quiet snapd.service; do sleep 1; done;
echo 'snapd.service is active and working.'
sleep 5
echo 'snapd is ready.'
sudo snap install --classic kubectx
sudo snap install --classic go